---
project_name: sensu-sql-check
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    binary: bin/sensu-sql-check
snapshot:
  name_template: "{{ .Tag }}"
checksum:
  name_template: checksums.txt
